### ISSUE TITLE
docs: parâmetro --save não é mais necessário nas versões mais atuais do NPM

### ISSUE THREAD

**Issue by mauromattos00** [totvs/po-theme-totvs#111]
## Descrição

Olá pessoal!

Sei que é uma modificação bem pequena, mas gostaria de ver o que vocês acham.

No README do repositório, temos a instrução de como instalar o pacote.

![image](https://user-images.githubusercontent.com/13375865/132783695-975ed5fb-e140-4bf6-af3b-f9aa8cbff649.png)

## Sugestão de Melhoria

À partir do NPM 5, a bibliotecas instaladas já são adicionadas como dependência do projeto por padrão, não havendo mais a necessidade do parâmetro `--save`.

Vocês acham que podemos remover o parâmetro da instrução do README?

Se acharem que vale a pena, posso abrir um PR com a modificação. 😃

**Comment by jhonyeduardo** [comment]
Boa tarde @mauromattos00 

Obrigado pela sugestão, fique a vontade de fazer a PR alteração :)

**Comment by jhonyeduardo** [comment]
https://github.com/totvs/po-theme-totvs/pull/112
