### ISSUE TITLE
Visual inconsistente após atualização

### ISSUE THREAD

**Issue by ademario** [totvs/po-theme-totvs#163]
Após atualização do po-ui para versao 14 e do @totvs/po-them para 5.22.7 o tema ficou alterado e também inconsistente em alguns pontos.
Exemplo:

Botões Com fundo azul no padrão passaram a ficar com fundo branco.
Visual do po-notification ficou irregular e com visibilidade ruim.

Antes estava na versão 5 do PO-UI e 5.10.0 do totvs-theme.

Fiz teste voltando a versão do tovs-theme  e mantendo a versão 14 do po-ui e o problema não resolveu.

usando o tema padrão do po-ui não ocorre os problemas indicados.

Anexo imagens do problema
![botoes](https://user-images.githubusercontent.com/7155067/180218072-7a41475b-91af-4cd5-8a94-98161ff0560f.png)
![notificacao](https://user-images.githubusercontent.com/7155067/180218090-fc2269ad-111a-4993-9196-27e8f0d06e34.png)
.

**Comment by ademario** [comment]
Complementando, habilitei o tema padrao do po-ui com variaveis e copiei o css do tema totvs para a aplicação. Os botoes ficaram corretos, a notificação melhorou , porém o detalhe nao fica tão visivel.
![tema-copiado-botoes](https://user-images.githubusercontent.com/7155067/180225937-ac7001dc-3ea5-46ea-a9aa-d2202ca12ea8.png)
![tema-copaido-notification](https://user-images.githubusercontent.com/7155067/180225941-0c6ba2da-d594-417a-9682-7fd80fb93dea.png)

Desta forma, creio que há algum problema ao carrega o thema da totvs direto no angular.json

**Comment by keinou** [comment]
+1

**Comment by kalelchavestotvs** [comment]
Mesmo problema para mim, resolvi utilizando no po-ui e po-theme-totvs as versões 14.0.0-rc.0.
Caso eu utilize as ultimas lançadas 14.1.0 o visual fica todo quebrado.
![image](https://user-images.githubusercontent.com/82214796/181254291-f6803702-37bd-4dfe-a121-21c278d7fa24.png)

![image](https://user-images.githubusercontent.com/82214796/181254605-1a8ad41d-dcae-4cfa-b030-7f4088b9d0c9.png)

**Comment by Kleger** [comment]
Estou tendo o mesmo problema após atualizar o tema para a versão 14.2.0.
![image](https://user-images.githubusercontent.com/8365266/182382352-6c4e1e79-7bcf-496e-a010-e97544d55cf8.png)

**Comment by alinelariguet** [comment]
Bom dia! @ademario @Kleger @kalelchavestotvs
Alguns testes podem ser feitos:
- Por favor verifiquem as versões dos pacotes `@po-ui/style`,`@po-ui/ng-components` e `@totvs/po-theme` dentro  da node_modules, elas devem estar iguais.
- Também pode ser necessário fazer uma instalação limpa apagando a pasta `node_modules`, o `package-lock.json` e a pasta `angular` e instalar novamente.
- Abrir em uma guia anônima do browser.

Me enviem por aqui o resultado que vocês obtiveram e caso necessário analisamos caso a caso.

**Comment by Kleger** [comment]
> Bom dia! @ademario @Kleger @kalelchavestotvs @keinou Alguns testes podem ser feitos:
> 
> * Por favor verifiquem as versões dos pacotes `@po-ui/style`,`@po-ui/ng-components` e `@totvs/po-theme` dentro  da node_modules, elas devem estar iguais.
> * Também pode ser necessário fazer uma instalação limpa apagando a pasta `node_modules`, o `package-lock.json` e a pasta `angular` e instalar novamente.
> * Abrir em uma guia anônima do browser.
> 
> Me enviem por aqui o resultado que vocês obtiveram e caso necessário analisamos caso a caso.

Olá @alinelariguet, fiz todos esses procedimentos e o resultado foi o mesmo. Os pacotes do PO UI estão todos na versão 14.2.0.
Alterei o estilo para o PO-UI para ver se também ocorria esse problema e não ocorre. Parece ser só quando utilizado o @totvs/po-theme.

**Comment by alinelariguet** [comment]
Boa tarde pessoal, por favor, quem puder realizar o seguinte teste:
- no arquivo angular.json alterar o styles para:
- "styles": [
              "./node_modules/@totvs/po-theme/css/po-theme-default-variables.min.css",
              "./node_modules/@totvs/po-theme/css/po-theme-default.min.css",
              "./node_modules/@po-ui/style/css/po-theme-core.min.css",
              ... < -  arquivo css raiz da aplicação, manter como está
              ],
Me enviem o resultado por favor.

**Comment by Kleger** [comment]
Boa tarde @alinelariguet,
Aplicando esses estilos o problema nos botões foi resolvido conforme pode ver na imagem abaixo. 
![image](https://user-images.githubusercontent.com/8365266/182951693-e582a24e-57b3-433f-aebd-b7366964b934.png)

Mas tem algumas questões mencionadas pelos colegas que continuam, como o overlay roxo no padrão do PO UI, e as cores das ações nas notificações estão em azul, o que destoa um pouco do vermelho dos erros. Não sei se é intencional, mas acredito que isso sejam melhorias de estilo que possa estar faltando no tema da Totvs.
![image](https://user-images.githubusercontent.com/8365266/182953892-528c87a5-6ce9-4641-adfc-ddc61363746f.png)

**Comment by DanielSartori** [comment]
Estou com o mesmmo problema de fundo roxo !

**Comment by alinelariguet** [comment]
Vamos verificar as situações reportadas acima e logo daremos um retorno.

**Comment by Dadinel** [comment]
@alinelariguet A alteração que você sugeriu de alterar o styles corrigiu diversos erros de css:
```
"styles": [
"./node_modules/@totvs/po-theme/css/po-theme-default-variables.min.css",
"./node_modules/@totvs/po-theme/css/po-theme-default.min.css",
"./node_modules/@po-ui/style/css/po-theme-core.min.css",
```

Porém eu concordo que as cores `po-notification` estão estranhas, principalmente o de erro.

Eu gostaria aqui, apenas ressaltar, que caso o padrão agora seja informar esses três arquivos de style, seria legal atualizar o _README_ do projeto **po-theme-totvs**, pois nele é indicado usar apenas um.

**Comment by kalelchavestotvs** [comment]
Boa tarde!
@alinelariguet as alterações sugeridas acima ficaram ok, estou testando com ng-components 14.3.0 e po-theme 14.3.0 também. Porém o problema no fundo rosado nos loadings permanece. Desta forma não posso usar a ultima versão do po-ui 😢

**Comment by cmregazzo** [comment]
Boa Tarde,

Aqui também estamos com problema na identidade visual do tema "azul" padrão da Totvs.

Fizemos a atualização do projeto para a versão 14.1.3 do Angular e para versão do 14.3.0 do PO-UI.

Fizemos os procedimentos citados acima, e mesmo assim vários componentes estão com problema visual.

O Combo do Table (p-selectable), está com o check decentralizado, o botões e labels estão com um contorno azul "estranho", o Information do Notification não está exibindo a mensagem na tela, a barra de progresso do Upload não é alimentada conforme o arquivo vai sendo carregado, etc.

Quando é executado o comando ng serve, esta sendo gerado os warnings abaixo:

./node_modules/@totvs/po-theme/css/po-theme-default.min.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!./node_modules/@totvs/po-theme/css/po-theme-default.min.css - Warning: Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(1:46713) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.

./node_modules/@totvs/po-theme/css/po-theme-default.min.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!./node_modules/@totvs/po-theme/css/po-theme-default.min.css - Warning: Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(1:58671) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.

./node_modules/@totvs/po-theme/css/po-theme-default.min.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!./node_modules/@totvs/po-theme/css/po-theme-default.min.css - Warning: Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(1:86704) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.

./node_modules/@totvs/po-theme/css/po-theme-default.min.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!./node_modules/@totvs/po-theme/css/po-theme-default.min.css - Warning: Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(1:165454) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.

./node_modules/@totvs/po-theme/css/po-theme-default.min.css.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!./node_modules/@totvs/po-theme/css/po-theme-default.min.css - Warning: Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(1:172401) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.

Vocês já tem alguma previsão de correção dos problemas? da forma que está infelizmente não é possível subir o projeto na ultima versão do PO-UI.

Obrigado.

No aguardo.

Cristian Regazzo

**Comment by alinelariguet** [comment]
Boa noite @Dadinel o readme do projeto já foi ajustado e estamos analisando para fazer esse ajuste de configuração já no update.
@cmregazzo sobre os problemas relatados me parece que não pegou as configurações ou está com o cache do Angular habilitado, importante apagar a pasta Angular gerada e subir a aplicação novamente, se o alinhamento estiver diferente do nosso portal deve ser algo relacionado a cache ou configuração.
Sobre o roxo no loading overlay já estamos corrigindo e assim que liberarmos já aviso por aqui também.
Sobre as cores do notification vou levar essas considerações para o time do AnimaliaDS para que possam reavaliar.

**Comment by alinelariguet** [comment]
Sobre o roxo no overlay, foi ajustado na versão 14.3.1. Estou fechando esta issue pois entendemos que as questões levantadas foram esclarecidas e/ou corrigidas. Caso necessário abrir uma nova issue.
