### ISSUE TITLE
Estilo divergência campo SELECT - 14.5.0

### ISSUE THREAD

**Issue by charlesreitz** [totvs/po-theme-totvs#180]
Fala Pessoa, alguém com problemas referente ao estilo da versão 14.5.0 ? 

![image](https://user-images.githubusercontent.com/1248135/192288983-83a69944-a1ab-46ff-ae2c-b26dc6c7c2d7.png)

![image](https://user-images.githubusercontent.com/1248135/192289102-49af0c60-dcfd-4fc5-870c-2fc7a270f7bf.png)

**Comment by guilnorth** [comment]
@charlesreitz percebi aqui também ao atualizar, conferindo as releases o motivo, apesar de estranho, foi acessibilidade: https://youtu.be/21-lJlEyzLY?t=716

**Comment by charlesreitz** [comment]
Olá! Realmente foi algo do UX. Obrigado!
