### ISSUE TITLE
Quebra de linha na string com espaço do label componente, po-radio-group

### ISSUE THREAD

**Issue by gabriesgomes** [totvs/po-theme-totvs#191]
Bom dia,

atualizei a versão do PO-UI para versão 14.8.0 e na label do componenete em questão ocorre a quebra de linha quando na string passada para o componente contém espaços.

Ex:
<img width="250" alt="Screenshot_57" src="https://user-images.githubusercontent.com/55770651/199016253-df20a070-c54b-4cc4-9ae9-ec8fabf81620.png">

<img width="250" alt="Screenshot_58" src="https://user-images.githubusercontent.com/55770651/199016443-5c1386a0-606c-42c9-867f-46ffb7580230.png">

Tentativa de correção aplicando propriedade: p-columns, p-size.

**Comment by RobertaPostai** [comment]
Bom Dia! novidades sobre esta correção?

**Comment by alinelariguet** [comment]
O problema relatado nesta issue não ocorre mais nas versões recentes.
