### ISSUE TITLE
Pacote publicado sem diretórios icons e images

### ISSUE THREAD

**Issue by lemissel** [totvs/po-theme-totvs#29]
Oi, tudo certo?

Acho que faltou o build antes de publicar o pacote, pois o pacote que está no NPM não está baixando os diretórios images e icons. Isso acaba quebrando o código.

Esse tema é bem bacana.

**Comment by jhonyeduardo** [comment]
Olá @lemissel 

Obrigado nos reportar, definimos o beta.1 como latest.

O beta.1 esta 100% atualizado com @po-ui/style, saiu beta.2 por questão de igualdade de versão, portanto não haverá problema ao utilizar beta.1.

Temos a como direção publicar versões por semana, logo teremos isso resolvido.

Fecharei a issue quando publicarmos a nova versão com a correção.

Qualquer dúvida estou a disposição.

**Comment by jhosefmarks** [comment]
Resolvido na PR #30
