### ISSUE TITLE
Erro ao executar o PO UI após aplicação do Tema da Totvs

### ISSUE THREAD

**Issue by andregesser95** [totvs/po-theme-totvs#51]
Bom dia,

Ao criar um novo projeto PO UI e aplicar o tema da totvs ao projeto, é me dado o seguinte erro ao startar o mesmo:

"PS C:\Meus Apps\ProjetoLogistica\projeto-escola> npm start

> projeto-escola@0.0.0 start C:\Meus Apps\ProjetoLogistica\projeto-escola
> ng serve

(node:9148) ExperimentalWarning: The fs.promises API is experimental

chunk {main} main.js, main.js.map (main) 13.9 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 141 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 381 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 5.57 MB [initial] [rendered]
Date: 2020-07-31T14:00:03.059Z - Hash: 2bd0e270abdab6a58078 - Time: 15596ms

WARNING in C:\Meus Apps\ProjetoLogistica\projeto-escola\node_modules\@po-ui\ng-components\__ivy_ngcc__\fesm2015\po-ui-ng-components.js depends on 'uuid'. CommonJS or AMD dependencies can cause optimization 
bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

ERROR in ./node_modules/@totvs/po-theme/css/po-theme-default.min.css (./node_modules/css-loader/dist/cjs.js??ref--13-1!./node_modules/postcss-loader/src??embedded!./node_modules/@totvs/po-theme/css/po-theme-default.min.css)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: C:\Meus Apps\ProjetoLogistica\projeto-escola\node_modules\@totvs\po-theme\css\po-theme-default.min.css:1:140714: Can't resolve '../images/order-ascending.svg' in 'C:\Meus Apps\ProjetoLogistica\projeto-escola\node_modules\@totvs\po-theme\css'"

Como podemos resolver esse situação?

**Comment by jhonyeduardo** [comment]
Boa tarde

A versão 2.10.0 foi publicada com problema, a versão 2.10.1 corrige este problema.

Pedimos desculpa pelo o ocorrido, qualquer dúvida estamos a disposição.
